print("Pull up Audio reset (PD4)")
pio.pin.setdir(pio.OUTPUT, pio.PD_4)
pio.pin.sethigh(pio.PD_4)
print("Setup I2C")
speed = i2c.setup(0, i2c.SLOW)
print(speed)

print("I2C Start")
i2c.start(0)
print("Select I2C device 0x4A (Audio chip)");
i2c.address( 0, 0x4a, i2c.TRANSMITTER )
print("Send 0x01")
i2c.write( 0, 0x01)
i2c.stop(0)
print("Read byte")
i2c.start(0)
i2c.address( 0, 0x4a, i2c.RECEIVER )
byte = i2c.read(0,1)
i2c.stop(0)
print( string.format("%02X", string.byte(byte)) )
